### ISSUE TITLE
Ambiguous C language requirements

### ISSUE THREAD

**Issue by ryandesign** [asmotor/asmotor#12]
README.md says:

> ASMotor is a portable and generic assembler engine and development system written in ANSI C11

but CMakeLists.txt says:

> ```
> set (CMAKE_C_STANDARD 99)
> ```

Which C language standard is required—C99 or C11?

**Comment by ghost** [comment]
Fixed in a1b4c0144bbc5c730bf60512ee7eb7b780076fdf
