### ISSUE TITLE
Z80: Error "SECTION_FULL" if section size exceeds 16kB

### ISSUE THREAD

**Issue by anp59** [asmotor/asmotor#16]
First of all many thanks for the asmotor project. Great work for many retro friends!

I tried the cpm-loader program for my C128. That worked well. 
Then when I tested it with the current asmotor code (1.3.0.rc), the motorz80 program encountered the SECTION_FULL error when inserting binary data beyond the 16kB size. 
The cause of the problem was that z80_ParseOption() works with a local copy of the structure z80_XasmConfiguration and therefore only the default value 16kB of the section size was used in the assembler.

The changes concern 2 source files.
**z80_main.c**: line 31 (delete _static_) 
```c
SConfiguration
z80_XasmConfiguration = {
``` 
**z80_options.c**: line 31 (add _external_)
```c
external SConfiguration z80_XasmConfiguration;
``` 
These changes have eliminated the error for me and the program works.

:relaxed:

**Comment by csoren** [comment]
Thank you!

I have integrated your fix, which looks correct. It does highlight that there's several problems with the current implementation of that functionality, however. Handling the section size should be done in a completely different way now, but that is something for another day.
