### ISSUE TITLE
m68k branch offset wrong when ORG is used

### ISSUE THREAD

**Issue by atsampson** [asmotor/asmotor#17]
If the following is assembled with `motor68k -fb`:

```
	SECTION "main",CODE
	ORG $100
	bra target	; 100
	nop		; 104
	nop		; 106
	nop		; 108
	nop		; 10a
	nop		; 10c
	nop		; 10e
target:	rts		; 110
```

... then the `bra` instruction is assembled as `6000 0010`, which would jump to `$112`. If you remove the `ORG` then it's assembled correctly.

(Thanks for asmotor - I've been having a lot of fun writing 68k code with it lately!)

**Comment by csoren** [comment]
This is now fixed. This really should have been caught by one of the tests, but unfortunately that particular test was not correct.

**Comment by atsampson** [comment]
Great - thanks very much!
