### ISSUE TITLE
Issue in calculating fixed section placement/sizes

### ISSUE THREAD

**Issue by nitro2k01** [asmotor/asmotor#6]
This issue was discovered while trying to put each part of the Sega Genesis ROM header in a separate, fixed location section. However, this code fails. (Just these 4 lines alone should be sufficient to repro.)

```
SECTION "HDR_SERIALNUMBER",DATA[$180]
	DC.B	"012345678"			;ROM serial number

SECTION "HDR_CHECKSUM",DATA[$18E]
	DC.W	$1234				;16-bit Checksum (Address $000200+)
```

Compile with:
```
motor68k -otest.bin -fb test.asm
```

Output:
```
E0131 test.asm(7): Section "" cannot be placed at $18E
```
However, the string in the `HDR_SERIALNUMBER` section is only 9 bytes long, which should not overlap the next section by a good margin. Suspecting it might be an issue with alignment of sections I also tried:

```
SECTION "HDR_SERIALNUMBER",DATA[$182]
	DC.B	"012345678"			;ROM serial number

SECTION "HDR_CHECKSUM",DATA[$190]
	DC.W	$1234				;16-bit Checksum (Address $000200+)
```

Which gave the same error. In both cases, reducing the length of the string to 8 bytes got rid of the error. However, the following worked just fine, filling every single byte up until the next section.

```
SECTION "HDR_SERIALNUMBER",DATA[$180]
	DC.B	"0123456789ABCDEF"			;ROM serial number

SECTION "HDR_CHECKSUM",DATA[$190]
	DC.W	$1234				;16-bit Checksum (Address $000200+)
```

**Comment by csoren** [comment]
Thank you for this report.

The 68k assembler currently attempts to enforce 8 bytes alignment of sections because of how  AmigaOS does things. Most of these rules need to be moved to the linker, which actually knows what platform you're targeting. Also, these rules need to be disabled completely for sections fixed to an address.

**Comment by nitro2k01** [comment]
Thanks. Then I know how to work aorund it at least.

**Comment by csoren** [comment]
I have tagged a new release 1.0.4 that fixes this issue for fixed sections. Additionally, default alignment for regular sections when writing a binary is now an option.
