### ISSUE TITLE
compilation errors due to unresolved warnings and -Werr

### ISSUE THREAD

**Issue by nonchip** [asmotor/asmotor#7]
```
[ 32%] Building C object xasm/common/CMakeFiles/xasm.dir/tokens.c.o
xasm/common/tokens.c: In function 'parseSymbol':
common/tokens.c:308:9: error: 'strncpy' specified bound 257 equals destination size [-Werror=stringop-truncation]
  308 |         strncpy(lex_Current.value.string, str_String(symbolName), sizeof(lex_Current.value.string));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

pretty sure we're dealing with a simple off-by-one here, since `strncpy` shouldn't copy a maximum of `sizeof dest` chars if it's supposed to append a `\0` (which it is, since it's `strncpy`, not `memcpy`).

the same happens a bunch of other times too in `xlib/library.c`.

**Comment by csoren** [comment]
I think this may already be fixed. Can you try the develop branch please, if you're not already?

**Comment by nonchip** [comment]
aah you're using the branches that way around, ok yeah i was on master, will try. :D

**Comment by nonchip** [comment]
yeah um now (on develop) i'm getting different warnings:

```
xasm/common/parse_float_expression.c: In function 'parse_FloatExpression':
xasm/common/parse_float_expression.c:165:12: error: 'result' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  165 |     return result;
      |            ^~~~~~
cc1: all warnings being treated as errors
```

fixed that by initially assigning 0, next one:

```
xasm/common/section.c:394:23: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  394 |  uint32_t intValue = *(uint32_t *) &floatValue;
      |                       ^~~
```
(no idea how to fix that, it's a bit horrifying what you're trying to cast there tbh)

and so on, so yeah more warnings and earlier ones.

**Comment by csoren** [comment]
I think these must have been fixed in another repo. I've pulled in those changes to the develop branch. This version is what I'm currently using and considering merging to master soon

**Comment by nonchip** [comment]
given `xasm` isn't a submodule i'm not quite sure what you mean by "fixed in another repo"? i just checked out the develop branch and it doesn't compile due to those warnings.

**Comment by nonchip** [comment]
for the record this is what cmake came up with config-wise:
```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done

```

**Comment by csoren** [comment]
There have been updates in a cloned repo. I have just now pulled in those changes to the develop branch in this repo. Please pull again and make sure the util submodule is also updated

**Comment by nonchip** [comment]
aaaah, both github's master and develop branch weren't the "current" one gotcha :P

yup your new develop push made everything work :)

**Comment by csoren** [comment]
Sorry about the confusion. I need to switch to trunk based insted of git-flow and kill off the develop branch

**Comment by nonchip** [comment]
yeah i've used git-flow for far too long too. but turns out "make it so no development happens on the default branch" might help with that 1% of users who don't get what a release is, but doesn't outweigh the benefits of just having stable releases and the one branch that contains the latest stuff :P
