### ISSUE TITLE
Error installing: Build failure in tokens.c

### ISSUE THREAD

**Issue by kkuez** [asmotor/asmotor#9]
- Fresh Linux Mint 20 install
- just installed build-essentials
- this:

marcel@marcel-linux:/asmotor_bootstrap$ sudo sh install.sh 
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marcel/asmotor_bootstrap/build/cmake/release
Scanning dependencies of target util
[  1%] Building C object util/CMakeFiles/util.dir/crc32.c.o
[  1%] Building C object util/CMakeFiles/util.dir/file.c.o
[  2%] Building C object util/CMakeFiles/util.dir/fmath.c.o
[  3%] Building C object util/CMakeFiles/util.dir/map.c.o
[  4%] Building C object util/CMakeFiles/util.dir/mem.c.o
[  5%] Building C object util/CMakeFiles/util.dir/set.c.o
[  6%] Building C object util/CMakeFiles/util.dir/str.c.o
[  7%] Building C object util/CMakeFiles/util.dir/strcoll.c.o
[  8%] Building C object util/CMakeFiles/util.dir/strbuf.c.o
[  9%] Building C object util/CMakeFiles/util.dir/strings.c.o
[ 10%] Linking C static library libutil.a
[ 10%] Built target util
Scanning dependencies of target xasm
[ 11%] Building C object xasm/common/CMakeFiles/xasm.dir/amigaobject.c.o
[ 12%] Building C object xasm/common/CMakeFiles/xasm.dir/binaryobject.c.o
[ 13%] Building C object xasm/common/CMakeFiles/xasm.dir/dependency.c.o
[ 14%] Building C object xasm/common/CMakeFiles/xasm.dir/errors.c.o
[ 15%] Building C object xasm/common/CMakeFiles/xasm.dir/expression.c.o
[ 16%] Building C object xasm/common/CMakeFiles/xasm.dir/filestack.c.o
[ 17%] Building C object xasm/common/CMakeFiles/xasm.dir/lexer.c.o
[ 18%] Building C object xasm/common/CMakeFiles/xasm.dir/lexer_constants.c.o
[ 19%] Building C object xasm/common/CMakeFiles/xasm.dir/lexer_variadics.c.o
[ 20%] Building C object xasm/common/CMakeFiles/xasm.dir/linemap.c.o
[ 21%] Building C object xasm/common/CMakeFiles/xasm.dir/object.c.o
[ 22%] Building C object xasm/common/CMakeFiles/xasm.dir/options.c.o
[ 23%] Building C object xasm/common/CMakeFiles/xasm.dir/parse.c.o
[ 24%] Building C object xasm/common/CMakeFiles/xasm.dir/parse_block.c.o
[ 25%] Building C object xasm/common/CMakeFiles/xasm.dir/parse_directive.c.o
[ 26%] Building C object xasm/common/CMakeFiles/xasm.dir/parse_expression.c.o
[ 27%] Building C object xasm/common/CMakeFiles/xasm.dir/parse_string.c.o
[ 28%] Building C object xasm/common/CMakeFiles/xasm.dir/parse_symbol.c.o
[ 29%] Building C object xasm/common/CMakeFiles/xasm.dir/patch.c.o
[ 30%] Building C object xasm/common/CMakeFiles/xasm.dir/section.c.o
[ 31%] Building C object xasm/common/CMakeFiles/xasm.dir/symbol.c.o
[ 32%] Building C object xasm/common/CMakeFiles/xasm.dir/tokens.c.o
In file included from /usr/include/string.h:495,
                 from /home/marcel/asmotor_bootstrap/xasm/common/tokens.c:19:
In function ‘strncpy’,
    inlined from ‘parseSymbol’ at /home/marcel/asmotor_bootstrap/xasm/common/tokens.c:308:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 257 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [xasm/common/CMakeFiles/xasm.dir/build.make:336: xasm/common/CMakeFiles/xasm.dir/tokens.c.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:328: xasm/common/CMakeFiles/xasm.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2

"Fehler" (german) -> Error
Had to remove ~ because of markdown.

**Comment by csoren** [comment]
Unfortunately the master branch was not up to date, as I had been using git flow. I'm switching to trunk-based instead, and master should now be updated. Please pull and try again.

**Comment by ghost** [comment]
Closing, appears to work
